"""角色常量与全局配置"""

# 角色名称
ROLE_CARD1 = '一卡剪辑'
ROLE_CARD2 = '二卡剪辑'
ROLE_ASSISTANT = '剪辑助理'
ROLE_LEADER = '剪辑组长'
ROLE_SUB_LEADER = '小组长'

# 默认配额
DEFAULT_CARD1_QUOTA = 70
DEFAULT_CARD2_QUOTA = 120
DEFAULT_CARD1_OVER_PRICE = 20
DEFAULT_CARD1_SHORT_PENALTY = 50
DEFAULT_LEADER_EPS_PRICE = 20
DEFAULT_LEADER_PROJECT_BONUS = 100
